name: Release Zip Ball

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: python -m pip install -r requirements.txt --target ./biliMediaUrlFetch
    - name: Install Zip
      uses: montudor/action-zip@v1
    - name: Package lambda function
      run: |
        cd ./biliMediaUrlFetch
        zip -r ../lambda-function.zip .
    - name: Publish Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: Zipball
        name: LambdaFuncZipBall
        body: >
          Used to deploy on AWS Lambda function
        files: >
          ./lambda-function.zip
        allow_override: true
        gzip: false
